headersOrigin = "config"
redirectsOrigin = "config"
plugins = []

[functions]

[functions."*"]

[build]
publish = "/Users/vtolbert/Projects/@victortolbert/victortolbert.com/dist"
publishOrigin = "config"
command = "pnpm run build"
commandOrigin = "config"

[build.environment]
NODE_VERSION = "20"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/_nuxt/builds/meta/*"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/_nuxt/builds/*"

[headers.values]
cache-control = "public, max-age=1, immutable"

[[headers]]
for = "/_nuxt/*"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/manifest.webmanifest"

[headers.values]
Content-Type = "application/manifest+json"

[[redirects]]
from = "/__nuxt_error"
to = "/.netlify/functions/server"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*"
to = "/.netlify/functions/server"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]