<template>
  <Head>
    <Title>nuxt-api-party</Title>
    <!-- <Link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@exampledev/new.css@1.1.2/new.min.css" /> -->
  </Head>

  <header>
    <NuxtLink to="/examples/api-party">
      <h1 class="font-bold text-lg">
        nuxt-api-party
      </h1>
    </NuxtLink>
    <p class="mt-4">
      Requests are proxied by a Nuxt server route and passed back to the client.
      The playground uses <a href="https://jsonplaceholder.typicode.com/" class="font-medium hover:underline text-blue-500">JSON Placeholder</a>
      and <a href="https://petstore3.swagger.io/" class="font-medium hover:underline text-blue-500">Swagger Pet Store</a> as example APIs.
      The dynamic composables <code class="font-semibold">$jsonPlaceholder</code> and <code class="font-semibold">useJsonPlaceholderData</code>
      are generated by the module.
    </p>
  </header>

  <main class="mt-8">
    <NuxtPage />
  </main>
</template>
