export const STATUS_PENDING = 1
export const STATUS_PROCESSING = 2
export const STATUS_PAID = 3
export const STATUS_DENIED = 4
export const STATUS_PAYMENT_SCHEDULED = [STATUS_PENDING, STATUS_PROCESSING, STATUS_PAID]
