create table tasks (
  id serial PRIMARY KEY,
  created_at TIMESTAMP,
  title VARCHAR(255) NOT NULL,
  completed BOOLEAN NOT NULL,
  "user" VARCHAR(255),
);

create table public.tasks (
  id bigint generated by default as identity,
  created_at timestamp with time zone not null default now(),
  title text null,
  completed boolean null,
  "user" uuid null default gen_random_uuid(),
  constraint temp_pkey primary key (id)
  ) tablespace pg_default;

insert into public.tasks (title, completed, "user", created_at) VALUES
('Buy groceries', true, 'Alice', '2024-02-02 10:00:00'),
('Finish report', false, 'Bob', '2024-02-01 15:30:00'),
('Go to the gym', true, 'Charlie', '2024-01-31 17:45:00'),
('Read a book', false, 'Alice', '2024-01-30 19:15:00'),
('Call mom', false, 'David', '2024-01-29 12:20:00'),
('Pay bills', true, 'Eve', '2024-01-28 08:55:00'),
('Write code', true, 'Frank', '2024-01-27 14:10:00'),
('Take a walk', false, 'Grace', '2024-01-26 16:25:00'),
('Clean the house', false, 'Hank', '2024-01-25 20:40:00'),
('Plan vacation', true, 'Ivy', '2024-01-24 09:30:00');
